# .gitpod.yml

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Workspace
    init: |
      source $HOME/miniconda/etc/profile.d/conda.sh
      conda activate dp_processing
      echo "Conda environment is activated."
    command: |
      echo "Running: $GITPOD_WORKSPACE_URL"
      # Any additional startup commands below

vscode:
  extensions:
    - mechatroner.rainbow-csv
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - Ikuyadeu.r-pack
    - codezombiech.gitignore # Language support for .gitignore files
    - esbenp.prettier-vscode # Markdown/CommonMark linting and style checking for Visual Studio Code
    - eamodio.gitlens # Quickly glimpse into whom, why, and when a line or code block was changed
    - EditorConfig.EditorConfig # Override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv # Highlight columns in csv files in different colors
    - nextflow.nextflow # Nextflow syntax highlighting
    - oderwat.indent-rainbow # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - GitHub.copilot # DESKTOP ONLY
    - reditorsupport.r
    - quarto.quarto