# .gitpod.yml
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - mechatroner.rainbow-csv
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==

    
tasks:
  - init: |
      conda env create -f environment.yml
    command: |
      source activate dp