# .gitpod.yml

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Workspace
    init: |
      # pip3 install -r requirements.txt
      conda config --set solver libmamba
      conda env create -f environment.yml
      echo "Conda environment is activated."
    command: |
      echo "Running: $GITPOD_WORKSPACE_URL"
      # Any additional startup commands below

vscode:
  extensions:
    - mechatroner.rainbow-csv
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - Ikuyadeu.r-pack