name: dp_processing
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  # Python Dependencies
  - python==3.10
  - jupyterlab==4.2.5
  - notebook==6.5.5
  - bash_kernel==0.9.3
  - coreutils==9.5
  - fastqc==0.12.1
  - multiqc==1.24.1
  - pip

  # Data Science Libraries
  - seaborn
  - plotly
  - matplotlib
  - pandas==1.5.0
  - scikit-learn
  - statsmodels
  - papermill

  # R Dependencies
  - r-base==4.4.1
  - r-irkernel==1.3.2
  - r-tidyverse==2.0.0

  # Conda Pip Extensions
  - pip:
    - jupyter_contrib_nbextensions==0.7.0
    - jupyter_nbextensions_configurator==0.6.3
    - nbclassic==0.4.8
